[package]
name = "molenest"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
anyhow = "1.0"
directories = "5.0"
serde = { version = "1.0", features = ["derive"] }
slint = "1.8"
time = { version = "0.3", features = ["formatting", "local-offset", "macros", "serde", "std"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
which = "6.0"

[build-dependencies]
slint-build = "1.8"
